[project]
name = "clarity-bitcoin"
description = "Clarity functions that help with reading and verifying transactions on the Bitcoin blockchain."
authors = []
telemetry = true
cache_dir = "./.cache"

[contracts.clarity-bitcoin]
path = "contracts/clarity-bitcoin.clar"
clarity_version = 1

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
