[project]
name = "counter"
description = "An on-chain counter function in Clarity that stores and increments a count on every transaction."
authors = []
telemetry = true
cache_dir = './.cache'

[contracts.counter]
path = "contracts/counter.clar"

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
