[project]
name = 'lightning-swaps-real'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.lightning-swaps-v1]
path = 'contracts/lightning-swaps-v1.clar'
clarity_version = 1
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
