[project]
name = 'lightning-swaps'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.stxswap_v10]
path = 'contracts/stxswap_v10.clar'
clarity_version = 1
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
