[project]
name = "lightning-swaps"
description = "A submarine swap implementation to provide a fast, private way of swapping Lightning Network Bitcoin for Stacks and vice versa."
authors = []
telemetry = true
cache_dir = "./.cache"

[contracts.stxswap_v10]
path = "contracts/stxswap_v10.clar"
clarity_version = 1

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
