[project]
name = "blank-project"
description = "A blank project conforms to Clarinet-compliant project structure"
authors = []
telemetry = true
cache_dir = "./.cache"

# [contracts.CHANGE-THIS-TO-YOUR-CONTRACT-NAME]
# path = "contracts/CHANGE-THIS-TO-YOUR-CONTRACT-NAME.clar"

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
